### ISSUE TITLE
Tracking documentation typos

### ISSUE THREAD

**Issue by dcpurton** [dcpurton/scripture#94]
- [x] Under **Hacks and Workarounds** the hyperlink to the stack exchange question isn't printed.
- [x] The `indent` option is not correctly sorted.
- [x] Remove space in `0.5 em` with the `poetry/verse/sep` option.
- [x] Remove space in `1 em` with `reference/start/sep` option.
- [x] Remove space in `0 pt` with `reference/start/vsep` option.
- [x] Add `lang=en` to `\DocumentMetadata`
- [x] Change date added for `\heading` function.
- [x] remove two erroneous `extraskip` begins a new paragraph…
- [x] Check things under `poetry/verse/...` option descriptions
- [x] `reference/start/vsep` typo
- [x] remove unnecessary double setting of `\listparindent` in environments which was used to work around quirk of `l3doc`
- [x] Check `chapter/para` changelog date
- [x] Add required fonts and where to get them from for building documentation to README.md
- [x] Check change log for anything missing
- [x] Extra `\end{document}` in `issue84.lvt`
- [x] More hyperlinks in docs
